# Generated by Django 4.0.3 on 2022-03-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributors',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issues',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
